### ISSUE TITLE
JSONObject["instanceBootTimeoutLimit"] is not a number.

### ISSUE THREAD

**Issue by ebrahim-moshaya** [jenkinsci/ec2-cloud-axis-plugin#5]
I am trying to use the ec2-axist with a matrix job. However, everytime I save the configured job I get stack trace. Please see screenshots below:

JSONObject["instanceBootTimeoutLimit"] is not a number.

net.sf.json.JSONException: JSONObject["instanceBootTimeoutLimit"] is not a number.
	at net.sf.json.JSONObject.getInt(JSONObject.java:1969)
	at org.jenkinsci.plugins.ec2axis.EC2Axis$DescriptorImpl.newInstance(EC2Axis.java:172)
	at org.jenkinsci.plugins.ec2axis.EC2Axis$DescriptorImpl.newInstance(EC2Axis.java:162)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:941)
	at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:903)

![ec2axis1](https://cloud.githubusercontent.com/assets/8818542/9542608/376fae34-4d6a-11e5-84ce-2e9c8d446276.jpg)
![ec2axis2](https://cloud.githubusercontent.com/assets/8818542/9542609/37708386-4d6a-11e5-8fab-0d4947c1d914.jpg)

**Comment by taksan** [comment]
Hi, I look into it. Thanks for reporting
